from __future__ import annotations

from enum import StrEnum


class ActionClass(StrEnum):
    READ_ONLY_LOCAL = "READ_ONLY_LOCAL"
    READ_ONLY_EXTERNAL = "READ_ONLY_EXTERNAL"
    NAVIGATION_ONLY = "NAVIGATION_ONLY"
    NON_DESTRUCTIVE_TOOL_USE = "NON_DESTRUCTIVE_TOOL_USE"
    CREDENTIALED_ACTION = "CREDENTIALED_ACTION"
    EXTERNAL_STATE_MUTATION = "EXTERNAL_STATE_MUTATION"
    DESTRUCTIVE_ACTION = "DESTRUCTIVE_ACTION"
    DURABLE_INTERNAL_STATE_MUTATION = "DURABLE_INTERNAL_STATE_MUTATION"
